FROM scratch

ARG TARGETPLATFORM

ENV PUID=1000
ENV PGID=1000
ENV FLATNOTES_HOST=0.0.0.0
ENV FLATNOTES_PORT=8080
ENV FLATNOTES_PATH=/data

VOLUME /data
EXPOSE 8080/tcp
COPY ${TARGETPLATFORM}/flatnotes-go /flatnotes-go
HEALTHCHECK --interval=60s --timeout=10s CMD ["/flatnotes-go", "healthcheck"]

ENTRYPOINT [ "/flatnotes-go" ]
