ARG BUILD_DIR=/build

# Client Build Container
FROM --platform=$BUILDPLATFORM node:20-alpine AS client-build

ARG BUILD_DIR

RUN mkdir ${BUILD_DIR}
WORKDIR ${BUILD_DIR}

COPY .htmlnanorc \
    package.json \
    package-lock.json \
    postcss.config.js \
    tailwind.config.js \
    vite.config.js \
    ./

RUN npm ci

COPY client ./client
RUN npm run build

# Server Build Container
FROM --platform=$BUILDPLATFORM golang:1.25.10-alpine AS server-build

ARG BUILD_DIR

WORKDIR ${BUILD_DIR}

COPY go.mod go.sum ./
RUN go mod download

COPY cmd ./cmd
COPY internal ./internal
COPY --from=client-build ${BUILD_DIR}/client/dist ./internal/web/dist
RUN CGO_ENABLED=0 go build -o /flatnotes-go ./cmd/flatnotes-go

# Runtime Container
FROM scratch

ENV FLATNOTES_HOST=0.0.0.0
ENV FLATNOTES_PORT=8080
ENV FLATNOTES_PATH=/data

USER 1000:1000
VOLUME /data
EXPOSE 8080/tcp
COPY --from=server-build /flatnotes-go /flatnotes-go
HEALTHCHECK --interval=60s --timeout=10s CMD ["/flatnotes-go", "healthcheck"]

ENTRYPOINT [ "/flatnotes-go" ]
